parameters:
#    map2u_leaflet.example.class: Map2u\LeafletBundle\Example

services:
#    map2u_leaflet.example:
#        class: %map2u_leaflet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
